import { SignInButton, SignOutButton, useUser } from "@clerk/nextjs";
import Head from "next/head";
import relativeTime from "dayjs/plugin/relativeTime";

import { type RouterOutputs, api } from "~/utils/api";
import dayjs from "dayjs";
import Image from "next/image";

dayjs.extend(relativeTime);

type PostWithUser = RouterOutputs["post"]["getAll"][number];

export default function Home() {
  const { data, isLoading } = api.post.getAll.useQuery();

  const user = useUser();

  if (isLoading) {
    return <p>Loading...</p>;
  }

  if (!data) {
    return <p>Something went wrong</p>;
  }

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center bg-slate-900">
        <div>{user.isSignedIn ? <SignOutButton /> : <SignInButton />}</div>

        <div className="w-full border border-white md:max-w-screen-lg">
          {user.isSignedIn && (
            <div className="flex flex-row gap-4 border-b p-4">
              <Image
                src={user.user.imageUrl}
                alt="Profile Image"
                height={56}
                width={56}
                className="h-14 w-14 rounded-full"
              />

              <input
                type="text"
                className="grow bg-transparent outline-none"
                placeholder="Type some emojis"
              />
            </div>
          )}

          <div>
            {data?.map(
              ({ post, user: { imageUrl, username, firstName, lastName } }) => {
                return (
                  <div key={post.id} className="flex flex-row gap-4 p-6">
                    <Image
                      src={imageUrl}
                      alt="Profile Image"
                      height={56}
                      width={56}
                      className="h-14 w-14 rounded-full"
                    />

                    <div className="flex flex-col gap-2">
                      <div>
                        <span>{username ?? `${firstName} ${lastName}`}</span>
                        <span> · </span>
                        <span className="font-thin">
                          {" "}
                          {dayjs(post.createdAt).fromNow()}{" "}
                        </span>
                      </div>

                      <div>{post.content}</div>
                    </div>
                  </div>
                );
              },
            )}
          </div>
        </div>
      </main>
    </>
  );
}
